http://stackoverflow.com/questions/34240703/difference-between-tensorflow-tf-nn-softmax-and-tf-nn-softmax-cross-entropy-with

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
sess = tf.Session()
y_hat = tf.convert_to_tensor(np.array([[0.5, 1.5, 0.1], [2.2, 1.3, 1.7]]))
sess.run(y_hat)

array([[ 0.5,  1.5,  0.1],
       [ 2.2,  1.3,  1.7]])

In [8]:
y_hat_softmax = tf.nn.softmax(y_hat)
sess.run(y_hat_softmax)

array([[ 0.227863  ,  0.61939586,  0.15274114],
       [ 0.49674623,  0.20196195,  0.30129182]])

In [10]:
y_true = tf.convert_to_tensor(np.array([[0.0, 1.0, 0.0],[0.0, 0.0, 1.0]]))
sess.run(y_true)

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [24]:
loss_per_instance_1 = -tf.reduce_sum(y_true * tf.log(y_hat_softmax), reduction_indices=[1])
sess.run(loss_per_instance_1)

array([ 0.4790107 ,  1.19967598])

In [16]:
total_loss_1 = tf.reduce_mean(-tf.reduce_sum(y_true * tf.log(y_hat_softmax), reduction_indices=[1]))
sess.run(total_loss_1)

0.83934333897877944

In [20]:
loss_per_instance_2 = tf.nn.softmax_cross_entropy_with_logits(logits=y_hat, labels=y_true)
sess.run(loss_per_instance_2)

array([ 0.4790107 ,  1.19967598])

In [22]:
total_loss_2 = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=y_hat, labels=y_true))
sess.run(total_loss_2)

0.83934333897877922